"""BuyerActor (SINGLETON) — runs deterministic MCDA over candidate pool.

This is the CENTRALIZED decision maker. Only ONE instance runs per procurement.
Implements the deterministic Multi-Criteria Decision Analysis over the distributed
candidate pool generated by Scouts, Evaluators, and Negotiators.
"""

from __future__ import annotations

from typing import Any

import ray
import structlog

from core.protocol.policy_engine import PolicyEngine
from mesh.actors.base import MeshActor
from mesh.blackboard import DistributedBlackboard
from mesh.channels import ChannelType
from swarm.domain.governance import STANDARD_POLICY, GovernancePolicy

logger = structlog.get_logger(__name__)


@ray.remote(max_restarts=0, max_task_retries=0)  # Singleton - no restarts
class BuyerActor(MeshActor):
    """The Buyer archetype performs deterministic MCDA over the distributed candidate pool.

    This replaces the central DecisionAgent with the same deterministic logic,
    but operating over a richer candidate pool generated by distributed actors.

    Key properties:
    - SINGLETON: Only one instance per procurement run
    - DETERMINISTIC: Same inputs always produce same output
    - MCDA: Multi-Criteria Decision Analysis (not quorum voting)
    - POLICY ENFORCEMENT: Governance policy applied as hard filter
    """

    def __init__(
        self,
        actor_id: str,
        blackboard: ray.actor.ActorHandle,
        kernel: ray.actor.ActorHandle | None = None,
        policy: GovernancePolicy | None = None,
    ) -> None:
        super().__init__(actor_id, "buyer", blackboard, kernel)
        self.policy = policy if policy is not None else STANDARD_POLICY
        self._policy_engine = PolicyEngine()

        # MCDA scoring weights (deterministic, from core evaluator)
        self.scoring_weights = {
            "price": 0.40,
            "lead_time": 0.25,
            "esg": 0.20,
            "reliability": 0.15,
        }
        self._processed_decisions: set[str] = set()

    async def perceive(self, blackboard: DistributedBlackboard) -> dict[str, Any]:
        """Read DEAL, RISK, and SCORE channels for all candidates."""
        deals = await self.read_channel(ChannelType.DEAL, limit=100)
        risks = await self.read_channel(ChannelType.RISK, limit=100)
        scores = await self.read_channel(ChannelType.SCORE, limit=100)

        return {
            "deals": deals,
            "risks": risks,
            "scores": scores,
        }

    async def reason(self, perception: dict[str, Any]) -> dict[str, Any]:
        """Deterministic MCDA over all candidates."""
        deals = perception.get("deals", [])
        risks = perception.get("risks", [])
        scores = perception.get("scores", [])

        # Group by correlation_id (one procurement run)
        by_correlation: dict[str, dict[str, Any]] = {}

        # Index deals by correlation_id and supplier_id
        for deal_trace in deals:
            payload = deal_trace.get("payload", {})
            if payload.get("type") != "quote":
                continue
            corr_id = deal_trace.get("correlation_id", "")
            supplier_id = str(payload.get("supplier_id", ""))
            if not corr_id or not supplier_id:
                continue
            if corr_id not in by_correlation:
                by_correlation[corr_id] = {"deals": {}, "risks": {}, "scores": {}}
            by_correlation[corr_id]["deals"][supplier_id] = deal_trace

        # Index risks
        for risk_trace in risks:
            payload = risk_trace.get("payload", {})
            if payload.get("type") != "risk_assessment":
                continue
            corr_id = risk_trace.get("correlation_id", "")
            supplier_id = str(payload.get("supplier_id", ""))
            if corr_id in by_correlation and supplier_id:
                by_correlation[corr_id]["risks"][supplier_id] = risk_trace

        # Index scores
        for score_trace in scores:
            payload = score_trace.get("payload", {})
            if payload.get("type") != "evaluation":
                continue
            corr_id = score_trace.get("correlation_id", "")
            supplier_id = str(payload.get("supplier_id", ""))
            if corr_id in by_correlation and supplier_id:
                by_correlation[corr_id]["scores"][supplier_id] = score_trace

        proposals = []

        for corr_id, data in by_correlation.items():
            if corr_id in self._processed_decisions:
                continue

            deals_map = data["deals"]
            risks_map = data["risks"]
            scores_map = data["scores"]

            if not deals_map:
                continue

            # Build candidate pool
            candidates = []
            for supplier_id, deal_trace in deals_map.items():
                score_trace = scores_map.get(supplier_id)
                risk_trace = risks_map.get(supplier_id)

                if not score_trace:
                    logger.warning(
                        "buyer_missing_score",
                        actor_id=self.actor_id,
                        correlation_id=corr_id,
                        supplier_id=supplier_id,
                    )
                    continue

                deal_data = deal_trace.get("payload", {}).get("data", {})
                score_data = score_trace.get("payload", {}).get("data", {})
                risk_data = risk_trace.get("payload", {}).get("data", {}) if risk_trace else None

                composite = self._compute_composite_score(deal_data, score_data, risk_data)

                candidates.append(
                    {
                        "supplier_id": supplier_id,
                        "composite_score": composite,
                        "deal": deal_data,
                        "risk": risk_data,
                        "score": score_data,
                        "deal_trace_id": deal_trace.get("id", ""),
                        "risk_trace_id": risk_trace.get("id", "") if risk_trace else "",
                        "score_trace_id": score_trace.get("id", ""),
                    }
                )

            if not candidates:
                proposals.append(
                    {
                        "correlation_id": corr_id,
                        "action": "insufficient_candidates",
                        "reason": "No scored suppliers available",
                        "confidence": 1.0,
                    }
                )
                continue

            # Policy filter (GovernancePolicy)
            valid_candidates = [c for c in candidates if self._passes_policy_filter(c)]

            if not valid_candidates:
                proposals.append(
                    {
                        "correlation_id": corr_id,
                        "action": "policy_rejection",
                        "reason": "No candidates pass governance policy",
                        "confidence": 1.0,
                    }
                )
                continue

            # Deterministic argmax with tie-breaker: lower supplier_id wins
            winner = max(
                valid_candidates,
                key=lambda c: (
                    c["composite_score"],
                    -ord(c["supplier_id"][0]) if c["supplier_id"] else 0,
                ),
            )

            # Ranked list for explanation
            ranked = sorted(
                candidates,
                key=lambda c: (-c["composite_score"], c["supplier_id"]),
            )

            proposals.append(
                {
                    "correlation_id": corr_id,
                    "action": "decision",
                    "selected_supplier": winner["supplier_id"],
                    "composite_score": winner["composite_score"],
                    "ranked": ranked,
                    "method": "deterministic_mcda",
                    "policy_applied": self.policy.name,
                    "confidence": 1.0,
                }
            )
            self._processed_decisions.add(corr_id)

        return {"proposals": proposals}

    async def act(self, blackboard: DistributedBlackboard, proposal: dict[str, Any]) -> None:
        """Write decision to DECISION channel."""
        for prop in proposal.get("proposals", []):
            correlation_id = prop["correlation_id"]
            action = prop["action"]

            if action == "decision":
                selected = prop["selected_supplier"]
                parent_ids = [c["deal_trace_id"] for c in prop["ranked"] if c["deal_trace_id"]]
                parent_ids.extend(
                    c["score_trace_id"] for c in prop["ranked"] if c["score_trace_id"]
                )
                parent_ids.extend(c["risk_trace_id"] for c in prop["ranked"] if c["risk_trace_id"])

                trace_id = await self.write_channel(
                    ChannelType.DECISION,
                    {
                        "type": "decision",
                        "data": {
                            "selected_supplier": selected,
                            "composite_score": prop["composite_score"],
                            "ranked": prop["ranked"],
                            "method": prop["method"],
                            "policy_applied": prop["policy_applied"],
                        },
                        "correlation_id": correlation_id,
                    },
                    parent_ids=parent_ids,
                )

                logger.info(
                    "buyer_decided",
                    actor_id=self.actor_id,
                    correlation_id=correlation_id,
                    selected_supplier=selected,
                    composite_score=prop["composite_score"],
                    trace_id=trace_id,
                )

            elif action in ("insufficient_candidates", "policy_rejection"):
                await self.write_channel(
                    ChannelType.DECISION,
                    {
                        "type": "decision",
                        "data": {
                            "selected_supplier": None,
                            "reason": prop["reason"],
                            "action": action,
                        },
                        "correlation_id": correlation_id,
                    },
                )
                logger.warning(
                    "buyer_no_award",
                    actor_id=self.actor_id,
                    correlation_id=correlation_id,
                    action=action,
                    reason=prop["reason"],
                )

    def _compute_composite_score(
        self, deal: dict[str, Any], score: dict[str, Any], risk: dict[str, Any] | None
    ) -> float:
        """Deterministic weighted scoring — identical to core/evaluator/scoring.py."""
        price = float(deal.get("price", 0.0))
        budget = float(deal.get("metadata", {}).get("quantity", 1)) * price
        if budget == 0:
            budget = price

        price_score = 1.0 - (price / budget) if budget > 0 else 0.0
        price_score = max(0.0, min(1.0, price_score))

        lead_time_score: float = score.get("breakdown", {}).get("lead_time", 0.5)
        esg_score: float = score.get("breakdown", {}).get("esg", 0.5)
        reliability_score: float = score.get("breakdown", {}).get("reliability", 0.5)

        composite: float = (
            self.scoring_weights["price"] * price_score
            + self.scoring_weights["lead_time"] * lead_time_score
            + self.scoring_weights["esg"] * esg_score
            + self.scoring_weights["reliability"] * reliability_score
        )

        # Risk adjustment (deterministic)
        if risk:
            risk_penalty: float = risk.get("risk_scores", {}).get("overall_risk_score", 0.0) * 0.3
            composite *= 1.0 - risk_penalty

        return round(composite, 6)  # Explicit rounding for determinism

    def _passes_policy_filter(self, candidate: dict[str, Any]) -> bool:
        """Apply GovernancePolicy as hard filter."""
        risk = candidate.get("risk")
        if not risk:
            return False

        risk_level = risk.get("risk_level", "UNKNOWN")
        overall_risk = risk.get("risk_scores", {}).get("overall_risk_score", 1.0)
        purchase_amount = risk.get("purchase_amount", 0.0)

        # CRITICAL always rejected
        if risk_level == "CRITICAL":
            return False

        # Overall risk score above policy max rejected
        if overall_risk > self.policy.max_risk_score:
            return False

        # Purchase amount above policy max rejected
        return not purchase_amount > self.policy.max_purchase_amount
