"""Procurement domain layer for the Phase 2 adapter swarm.

Contains the domain artifacts, event types and the deterministic agents
(requirement, strategy, supplier discovery, evaluation, negotiation, decision,
risk, governance and approval) that wrap the existing ``core/`` procurement logic.
The agents communicate exclusively through the swarm runtime (``Message → Event →
Artifact``) and never call each other directly.
"""

from swarm.domain.agents import (
    ApprovalAgent,
    DecisionAgent,
    EvaluationAgent,
    ExecutionTrackingAgent,
    GovernanceAgent,
    NegotiationAgent,
    OutcomeAgent,
    PurchaseOrderAgent,
    RequirementAgent,
    RiskAssessmentAgent,
    StrategyAgent,
    SupplierDiscoveryAgent,
    SupplierIntelligenceAgent,
)
from swarm.domain.artifacts import (
    DECISION_ARTIFACT_NAME,
    DECISION_EXPLANATION_ARTIFACT_NAME,
    EXECUTION_AUTHORIZATION_ARTIFACT_NAME,
    EXECUTION_STATUS_ARTIFACT_NAME,
    GOVERNANCE_DECISION_ARTIFACT_NAME,
    OUTCOME_ARTIFACT_NAME,
    PURCHASE_ORDER_ARTIFACT_NAME,
    REQUIREMENT_ARTIFACT_NAME,
    RISK_ASSESSMENT_ARTIFACT_NAME,
    STRATEGY_ARTIFACT_NAME,
    SUPPLIER_LIST_ARTIFACT_NAME,
    SUPPLIER_PERFORMANCE_ARTIFACT_NAME,
    DecisionArtifact,
    DecisionExplanationArtifact,
    EvaluationArtifact,
    ExecutionAuthorizationArtifact,
    ExecutionStatusArtifact,
    GovernanceDecisionArtifact,
    OutcomeArtifact,
    PurchaseOrderArtifact,
    QuoteArtifact,
    RequirementArtifact,
    RiskAssessmentArtifact,
    StrategyArtifact,
    SupplierListArtifact,
    SupplierPerformanceArtifact,
    evaluation_artifact_name,
    quote_artifact_name,
)
from swarm.domain.events import (
    APPROVE_INTENT,
    CREATE_REQUIREMENT_INTENT,
    EXECUTE_INTENT,
    RECORD_OUTCOME_INTENT,
    ProcurementEventType,
)
from swarm.domain.governance import (
    DEFAULT_GOVERNANCE_POLICIES,
    STANDARD_POLICY,
    STRICT_POLICY,
    GovernanceDecision,
    GovernancePolicy,
    GovernanceStatus,
)
from swarm.domain.order import (
    OrderLine,
    PurchaseOrder,
    PurchaseStatus,
    SupplierConnector,
    default_connector,
    order_id_for,
    order_to_dict,
)
from swarm.domain.pricing import (
    DEFAULT_BID_BOND_PCT,
    DEFAULT_PAYMENT_TERMS,
    bid_bond_amount,
    carbon_footprint,
    floor_price,
    lead_time_days,
)
from swarm.domain.risk import (
    DEFAULT_NO_HISTORY_RISK,
    RISK_LEVEL_CRITICAL,
    RISK_LEVEL_HIGH,
    RISK_LEVEL_MEDIUM,
    RiskAssessment,
    RiskLevel,
    classify_risk,
    compute_risk_scores,
)
from swarm.domain.strategy import (
    BALANCED_STRATEGY,
    DEFAULT_STRATEGIES,
    Strategy,
    select_strategy,
)

__all__ = [
    "APPROVE_INTENT",
    "BALANCED_STRATEGY",
    "CREATE_REQUIREMENT_INTENT",
    "DECISION_ARTIFACT_NAME",
    "DECISION_EXPLANATION_ARTIFACT_NAME",
    "DEFAULT_BID_BOND_PCT",
    "DEFAULT_GOVERNANCE_POLICIES",
    "DEFAULT_NO_HISTORY_RISK",
    "DEFAULT_PAYMENT_TERMS",
    "DEFAULT_STRATEGIES",
    "EXECUTE_INTENT",
    "EXECUTION_AUTHORIZATION_ARTIFACT_NAME",
    "EXECUTION_STATUS_ARTIFACT_NAME",
    "GOVERNANCE_DECISION_ARTIFACT_NAME",
    "OUTCOME_ARTIFACT_NAME",
    "PURCHASE_ORDER_ARTIFACT_NAME",
    "RECORD_OUTCOME_INTENT",
    "REQUIREMENT_ARTIFACT_NAME",
    "RISK_ASSESSMENT_ARTIFACT_NAME",
    "RISK_LEVEL_CRITICAL",
    "RISK_LEVEL_HIGH",
    "RISK_LEVEL_MEDIUM",
    "STANDARD_POLICY",
    "STRICT_POLICY",
    "STRATEGY_ARTIFACT_NAME",
    "SUPPLIER_LIST_ARTIFACT_NAME",
    "SUPPLIER_PERFORMANCE_ARTIFACT_NAME",
    "ApprovalAgent",
    "DecisionAgent",
    "DecisionArtifact",
    "DecisionExplanationArtifact",
    "EvaluationAgent",
    "EvaluationArtifact",
    "ExecutionAuthorizationArtifact",
    "ExecutionStatusArtifact",
    "ExecutionTrackingAgent",
    "GovernanceAgent",
    "GovernanceDecision",
    "GovernanceDecisionArtifact",
    "GovernancePolicy",
    "GovernanceStatus",
    "NegotiationAgent",
    "OrderLine",
    "OutcomeAgent",
    "OutcomeArtifact",
    "ProcurementEventType",
    "PurchaseOrder",
    "PurchaseOrderAgent",
    "PurchaseOrderArtifact",
    "PurchaseStatus",
    "QuoteArtifact",
    "RequirementAgent",
    "RequirementArtifact",
    "RiskAssessment",
    "RiskAssessmentAgent",
    "RiskAssessmentArtifact",
    "RiskLevel",
    "Strategy",
    "StrategyAgent",
    "StrategyArtifact",
    "SupplierConnector",
    "SupplierDiscoveryAgent",
    "SupplierIntelligenceAgent",
    "SupplierListArtifact",
    "SupplierPerformanceArtifact",
    "bid_bond_amount",
    "carbon_footprint",
    "classify_risk",
    "compute_risk_scores",
    "default_connector",
    "evaluation_artifact_name",
    "floor_price",
    "lead_time_days",
    "order_id_for",
    "order_to_dict",
    "quote_artifact_name",
    "select_strategy",
]
